services:
  database:
    image: mariadb:latest #optionaly set specific version e.g. mariadb:10.7
    ports:
      - "3307:3306"
    networks:
      - db-tier
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_DATABASE: proactive
    container_name: myComposeMariaDB
    # Comment this if you do not want to attach a volume for persistent data storage:
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mariadb-admin" , "ping", "-h", "localhost", "--password=PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
  sal:
    #Set up image to be used for SAL from https://hub.docker.com/r/activeeon/sal/tags
    image: activeeon/sal:test
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    depends_on:
      database:
        condition: service_healthy
    ports:
      #Port for sal service
      - "8088:8080"
      #Port for sal-pda debugging service
      - "9001:9001"
    links:
      - "database:myComposeMariaDB"
    networks:
      - db-tier
    volumes:
      - ./scripts:/usr/local/tomcat/scripts
      - ./wait_for_db.sh:/usr/local/tomcat/bin/wait_for_db.sh
    environment:
      PROPERTIES_FILENAME: sal
      CLUSTER_TYPE: "k8s"  # (defult) or "k3s" 
      #Set up connection to ProActive server (PWS)
      PWS_URL: <CHANGE_ME>
      PWS_USERNAME: <CHANGE_ME>
      PWS_PASSWORD: <CHANGE_ME>
      DB_USERNAME: root
      DB_PASSWORD: PASSWORD
      DB_DRIVER_CLASSNAME: org.mariadb.jdbc.Driver
      DB_PORT: 3306
      DB_HOSTNAME: myComposeMariaDB
      DB_URL: jdbc:mariadb://myComposeMariaDB:3306/proactive
      DB_PLATFORM: org.hibernate.dialect.MariaDB53Dialect
      JPDA_ADDRESS: 9001
      JPDA_TRANSPORT: dt_socket
    entrypoint: [
      "/bin/sh",
      "-c",
      "chmod +x /usr/local/tomcat/bin/wait_for_db.sh && \
      if [ -f /usr/local/tomcat/bin/wait_for_db.sh ]; then /usr/local/tomcat/bin/wait_for_db.sh; fi && \
      export JPDA_OPTS='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:9001' && \
      catalina.sh jpda run"
    ]
    container_name: myComposeSAL
networks:
  db-tier: {}
#Comment this part if you do not want to include volume for peristant data storage
volumes:
  mariadb_data: {}
